// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_just_getting_started = "CgkI9IfZjt8OEAIQDQ"; // <GPGSID>
        public const string achievement_whos_the_boss = "CgkI9IfZjt8OEAIQEA"; // <GPGSID>
        public const string achievement_200_ok = "CgkI9IfZjt8OEAIQHQ"; // <GPGSID>
        public const string achievement_what_will_you_buy_for_it = "CgkI9IfZjt8OEAIQCw"; // <GPGSID>
        public const string achievement_your_first_100_coins = "CgkI9IfZjt8OEAIQCA"; // <GPGSID>
        public const string achievement_am_i_the_best_yet = "CgkI9IfZjt8OEAIQDg"; // <GPGSID>
        public const string achievement_enemies_have_no_chance_with_me = "CgkI9IfZjt8OEAIQFQ"; // <GPGSID>
        public const string achievement_10000_coins_is_yours = "CgkI9IfZjt8OEAIQCg"; // <GPGSID>
        public const string achievement_only_150_phi = "CgkI9IfZjt8OEAIQHA"; // <GPGSID>
        public const string achievement_collect_them_all = "CgkI9IfZjt8OEAIQGg"; // <GPGSID>
        public const string achievement_just_stop = "CgkI9IfZjt8OEAIQGA"; // <GPGSID>
        public const string achievement_jump_for_10_coins = "CgkI9IfZjt8OEAIQEw"; // <GPGSID>
        public const string achievement_you_are_on_the_road_to_being_a_millionaire = "CgkI9IfZjt8OEAIQCQ"; // <GPGSID>
        public const string leaderboard_leadertabletest = "CgkI9IfZjt8OEAIQHg"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkI9IfZjt8OEAIQAA"; // <GPGSID>
        public const string achievement_i_want_100_boosters = "CgkI9IfZjt8OEAIQGw"; // <GPGSID>
        public const string achievement_yeah_im_good_at_this_game = "CgkI9IfZjt8OEAIQEg"; // <GPGSID>
        public const string achievement_i_like_boosters = "CgkI9IfZjt8OEAIQGQ"; // <GPGSID>
        public const string achievement_omg_2000_points = "CgkI9IfZjt8OEAIQDw"; // <GPGSID>
        public const string achievement_you_are_a_millionaire = "CgkI9IfZjt8OEAIQDA"; // <GPGSID>
        public const string achievement_i_think_im_good_at_this_game = "CgkI9IfZjt8OEAIQEQ"; // <GPGSID>
        public const string achievement_i_will_beat_them_all = "CgkI9IfZjt8OEAIQFw"; // <GPGSID>
        public const string achievement_im_just_jumping = "CgkI9IfZjt8OEAIQFA"; // <GPGSID>
        public const string achievement_i_defeated_100_enemies = "CgkI9IfZjt8OEAIQFg"; // <GPGSID>

}

